# Generated by Django 4.2.7 on 2024-01-22 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupons',
            name='used_count',
        ),
    ]
