# Generated by Django 4.2.7 on 2024-01-22 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0002_remove_coupons_used_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupons',
            old_name='disount_value',
            new_name='discount_value',
        ),
    ]
