# Generated by Django 4.2.7 on 2024-01-23 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0003_rename_disount_value_coupons_discount_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupons',
            name='used_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
