# Generated by Django 4.2.7 on 2024-01-24 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0004_coupons_used_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponusage',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
