# Generated by Django 4.2.7 on 2024-02-02 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='title',
        ),
    ]
