# Generated by Django 4.2.7 on 2023-11-30 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAuthentication', '0003_customuser_fullname_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='fullname',
        ),
    ]
