# Generated by Django 4.2.7 on 2024-01-03 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuthentication', '0007_customuser_email_otp_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email_otp_timestamp',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_listed',
            field=models.BooleanField(default=True),
        ),
    ]
