# Generated by Django 4.2.7 on 2024-01-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuthentication', '0008_remove_customuser_email_otp_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_listed',
            field=models.BooleanField(default=False),
        ),
    ]
