# Generated by Django 4.2.7 on 2024-02-01 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuthentication', '0009_alter_customuser_is_listed'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='referal_id',
            field=models.CharField(blank=True, editable=False, max_length=7, null=True, unique=True),
        ),
    ]
