# Generated by Django 4.2.7 on 2024-02-01 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuthentication', '0010_customuser_referal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reffered',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
