# Generated by Django 4.2.7 on 2024-02-01 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuthentication', '0011_customuser_reffered'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reffered_id',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
