# Generated by Django 4.2.7 on 2023-12-30 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersitem',
            name='total_item_amount',
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
