# Generated by Django 4.2.7 on 2023-12-30 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_ordersitem_total_item_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersitem',
            name='status',
            field=models.CharField(default='Order confirmed', max_length=200),
        ),
    ]
