# Generated by Django 4.2.7 on 2023-12-07 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='colour',
            field=models.CharField(max_length=50),
        ),
    ]
