# Generated by Django 4.2.7 on 2023-12-20 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_rename_customer_cart_customuser'),
        ('products', '0005_rename_quantity_products_stock'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Productss',
        ),
    ]
