# Generated by Django 4.2.7 on 2023-12-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_products_productss'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productss',
            name='colour',
        ),
        migrations.AlterField(
            model_name='productss',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
