# Generated by Django 4.2.7 on 2023-12-20 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_rename_customer_cart_customuser'),
        ('products', '0007_remove_productss_colour_alter_productss_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Productss',
            new_name='Products',
        ),
    ]
