# Generated by Django 4.2.7 on 2024-01-30 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_products_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category_offer',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='products',
            name='product_offer',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='products',
            name='is_listed',
            field=models.BooleanField(default=False),
        ),
    ]
