# Generated by Django 4.2.7 on 2024-01-31 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_products_category_offer_products_product_offer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category_offer',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_offer',
            field=models.PositiveIntegerField(),
        ),
    ]
