# Generated by Django 4.2.7 on 2024-01-31 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_products_category_offer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='category_offer',
        ),
        migrations.AlterField(
            model_name='products',
            name='product_offer',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
